"""
ai_query_service.py — Core orchestration for Ask MicroFlow (Natural Language ML Assistant).

Workflow:
  1. Enforces domain constraint via explicit SUPPORTED_INTENTS whitelist.
  2. Invokes Gemini to extract structured intent and search filters.
  3. Immediately rejects unsupported queries without database queries or reasoning.
  4. Checks AIQueryCache via deterministic SHA-256 query hash.
  5. If uncached, invokes repository methods (zero SQL generated by Gemini) to synthesize
     authentic database results as the source of truth.
  6. Passes structured results to Gemini to generate professional engineering answers.
  7. Persists new response in AIQueryCache and returns.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from typing import Any

from fastapi import HTTPException, status
from sqlalchemy.orm import Session

from app.ai.cache_service import compute_prompt_hash
from app.ai.gemini_service import GeminiService
from app.ai.prompt_builder import build_intent_prompt, build_assistant_prompt
from app.ai.response_parser import parse_intent_response, parse_assistant_response
from app.ai.schemas import AIQueryResponse, ConversationMessage
from app.models.ai_query import AIQueryCache
from app.repositories.ai_query_repository import AIQueryRepository
from app.repositories.dataset_repository import DatasetRepository
from app.repositories.experiment_repository import ExperimentRepository
from app.repositories.run_repository import RunRepository
from app.repositories.run_result_repository import RunResultRepository

logger = logging.getLogger(__name__)

# Explicit whitelist of supported intents for the ML experimentation platform
SUPPORTED_INTENTS = {
    "datasets",
    "experiments",
    "runs",
    "metrics",
    "artifacts",
    "models",
    "training_history",
    "ai_reviews",
    "run_comparisons",
    "performance_summaries",
    "next_recommendation",
    "best_performing",
}


class AIQueryService:
    def __init__(
        self,
        query_repo: AIQueryRepository,
        dataset_repo: DatasetRepository,
        experiment_repo: ExperimentRepository,
        run_repo: RunRepository,
        run_result_repo: RunResultRepository,
        gemini_service: GeminiService,
    ) -> None:
        self._query_repo = query_repo
        self._dataset_repo = dataset_repo
        self._experiment_repo = experiment_repo
        self._run_repo = run_repo
        self._run_result_repo = run_result_repo
        self._gemini = gemini_service

    def _to_response(self, record: AIQueryCache, cached: bool) -> AIQueryResponse:
        return AIQueryResponse(
            id=record.id,
            question=record.question,
            intent=record.intent,
            answer=record.answer,
            reasoning=record.reasoning,
            supporting_data=record.supporting_data,
            recommendation=record.recommendation or "No further action required.",
            model_name=record.model_name,
            generated_at=record.created_at,
            cached=cached,
        )

    def _gather_structured_data(self, intent: str, filters: dict[str, Any], db: Session) -> str:
        """
        Execute existing Python repository methods to assemble authentic database records.
        No SQL is generated by Gemini or passed directly to PostgreSQL.
        """
        datasets = self._dataset_repo.list_all(db)
        experiments = self._experiment_repo.list_all(db)
        runs = self._run_repo.list_all(db)

        if not datasets and not experiments and not runs:
            return "Database contains 0 datasets, 0 experiments, and 0 training runs. No operational ML data has been recorded yet."

        # Map experiment names and datasets
        exp_map = {e.id: e for e in experiments}
        ds_map = {d.id: d for d in datasets}

        # Apply filters to runs
        filtered_runs = []
        for run in runs:
            if filters.get("model_type") and str(filters["model_type"]).lower() not in ("null", "none", ""):
                f_val = str(filters["model_type"]).lower().replace(" ", "").replace("_", "").replace("-", "")
                r_val = str(run.model_type or "").lower().replace(" ", "").replace("_", "").replace("-", "")
                if f_val and (f_val not in r_val and r_val not in f_val):
                    continue
            if filters.get("status") and str(filters["status"]).lower() not in ("null", "none", ""):
                if run.status.value.lower() != str(filters["status"]).lower():
                    continue
            filtered_runs.append(run)

        # Attach metrics
        run_items = []
        for run in filtered_runs:
            res = self._run_result_repo.get_by_run_id(run.id, db)
            exp = exp_map.get(run.experiment_id)
            exp_name = exp.name if exp else "Unknown Experiment"
            ds_name = "None"
            if exp and exp.dataset_id and exp.dataset_id in ds_map:
                ds_name = ds_map[exp.dataset_id].name
            run_items.append((run, res, exp_name, ds_name))

        # Sort runs if metric_sort specified, or fallback to accuracy for performance-driven inquiries
        metric_sort = str(filters.get("metric_sort") or "").lower()
        if not metric_sort or metric_sort in ("null", "none"):
            if intent in ("best_performing", "metrics", "performance_summaries", "models", "run_comparisons", "runs"):
                metric_sort = "accuracy"

        if metric_sort and metric_sort not in ("null", "none"):
            sort_key_map = {
                "accuracy": lambda item: item[1].accuracy if item[1] and item[1].accuracy is not None else -1,
                "f1_score": lambda item: item[1].f1_score if item[1] and item[1].f1_score is not None else -1,
                "precision": lambda item: item[1].precision if item[1] and item[1].precision is not None else -1,
                "recall": lambda item: item[1].recall if item[1] and item[1].recall is not None else -1,
                "roc_auc": lambda item: item[1].roc_auc if item[1] and item[1].roc_auc is not None else -1,
                "execution_time_seconds": lambda item: item[1].execution_time_seconds if item[1] and item[1].execution_time_seconds is not None else -1,
            }
            sort_fn = sort_key_map.get(metric_sort)
            if sort_fn:
                run_items.sort(key=sort_fn, reverse=True)

        lines = []
        lines.append(f"DATASETS SUMMARY (Total: {len(datasets)}):")
        for d in datasets[:15]:
            lines.append(f"- Dataset '{d.name}' (Rows: {d.row_count or 'Unknown'}, Cols: {d.column_count or 'Unknown'}, Status: {d.status.value})")

        lines.append(f"\nEXPERIMENTS SUMMARY (Total: {len(experiments)}):")
        for e in experiments[:20]:
            ds = ds_map.get(e.dataset_id)
            ds_str = f"Dataset: '{ds.name}'" if ds else "No Dataset"
            lines.append(f"- Experiment '{e.name}' (Status: {e.status.value}, {ds_str}, Objective: '{e.objective or 'None'}')")

        lines.append(f"\nTRAINING RUNS & METRICS (Showing {min(25, len(run_items))} of {len(run_items)} matching runs):")
        if not run_items:
            lines.append("- No runs matched the specified search filters.")
        else:
            for run, res, exp_name, ds_name in run_items[:25]:
                metrics_str = "No evaluation metrics recorded (run incomplete or failed)"
                if res:
                    acc = f"{res.accuracy:.4f}" if res.accuracy is not None else "N/A"
                    f1 = f"{res.f1_score:.4f}" if res.f1_score is not None else "N/A"
                    exec_t = f"{res.execution_time_seconds:.2f}s" if res.execution_time_seconds else "N/A"
                    metrics_str = f"Accuracy: {acc}, F1 Score: {f1}, Exec Time: {exec_t}"
                config_str = ", ".join([f"{k}={v}" for k, v in (run.training_configuration or {}).items()]) or "default config"
                lines.append(f"- Run #{run.run_number} (Experiment: '{exp_name}', Dataset: '{ds_name}') — Model: {run.model_type or 'N/A'} | Status: {run.status.value} | {metrics_str} | Config: [{config_str}]")

        return "\n".join(lines)

    def process_query(
        self,
        question: str,
        context: list[ConversationMessage] | None,
        db: Session,
    ) -> AIQueryResponse:
        """Process a natural language user query through intent extraction and answer generation."""
        if not question or not question.strip():
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Question cannot be empty.",
            )

        context_dicts = [{"role": m.role, "content": m.content} for m in context] if context else None

        # ── 1. Intent Extraction ──────────────────────────────────────────────
        logger.info("Extracting intent for query: %s", question[:100])
        try:
            intent_prompt = build_intent_prompt(question=question, context=context_dicts)
            raw_intent = self._gemini.extract_intent(intent_prompt)
            extracted = parse_intent_response(raw_intent)
        except Exception as exc:
            logger.warning("Intent extraction fallback due to error: %s", exc)
            # Fallback to broad analysis if extraction fails syntax
            from app.ai.schemas import IntentExtractionResult
            extracted = IntentExtractionResult(intent="performance_summaries", filters={}, reasoning_required=True)

        # ── 2. Validate against explicit Whitelist ────────────────────────────
        if extracted.intent == "unsupported" or extracted.intent not in SUPPORTED_INTENTS:
            logger.info("Query rejected as unsupported intent: '%s'", extracted.intent)
            return AIQueryResponse(
                id="unsupported",
                question=question,
                intent="unsupported",
                answer=(
                    "MicroFlow Assistant is specialized for machine learning experimentation. "
                    "I can help analyze datasets, experiments, runs, metrics, artifacts, "
                    "and provide recommendations based on the information available in this platform."
                ),
                reasoning="The submitted question falls outside the supported ML engineering domain of this platform.",
                supporting_data="No database queries were executed.",
                recommendation="Please ask a question regarding experiments, runs, models, or datasets.",
                model_name=self._gemini.model_name,
                generated_at=datetime.now(timezone.utc),
                cached=False,
            )

        # ── 3. Check Cache ────────────────────────────────────────────────────
        cache_key_str = f"{question.strip().lower()}:{extracted.intent}:{json.dumps(extracted.filters, sort_keys=True)}"
        query_hash = compute_prompt_hash(cache_key_str)
        cached_record = self._query_repo.get_by_hash(query_hash, db)
        if cached_record:
            logger.info("Returning cached AI assistant response for query hash: %s", query_hash[:8])
            return self._to_response(cached_record, cached=True)

        # ── 4. Execute Repositories (Source of Truth) ─────────────────────────
        structured_data = self._gather_structured_data(extracted.intent, extracted.filters, db)

        # ── 5. Generate Professional Answer via Gemini ────────────────────────
        logger.info("Generating fresh AI assistant answer (intent=%s)", extracted.intent)
        try:
            answer_prompt = build_assistant_prompt(
                question=question,
                intent=extracted.intent,
                structured_data=structured_data,
                context=context_dicts,
            )
            raw_answer = self._gemini.generate_answer(answer_prompt)
        except RuntimeError as exc:
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail=str(exc),
            ) from exc

        # ── 6. Parse and Validate Answer ──────────────────────────────────────
        try:
            parsed = parse_assistant_response(raw_answer)
        except ValueError as exc:
            logger.error("Failed to parse Gemini assistant JSON: %s", exc)
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail=f"AI assistant response could not be parsed: {exc}",
            ) from exc

        # ── 7. Persist to Cache ───────────────────────────────────────────────
        record = self._query_repo.create(
            db,
            query_hash=query_hash,
            question=question,
            intent=extracted.intent,
            filters_json=json.dumps(extracted.filters),
            model_name=self._gemini.model_name,
            answer=parsed["answer"],
            reasoning=parsed["reasoning"],
            supporting_data=parsed["supporting_data"],
            recommendation=parsed["recommendation"],
        )

        return self._to_response(record, cached=False)

    def get_recent_queries(self, limit: int, db: Session) -> list[AIQueryResponse]:
        records = self._query_repo.get_recent(limit, db)
        return [self._to_response(r, cached=True) for r in records]
